const wsTypes = {
    CREATE_CHARACTER: 'CREATE_CHARACTER',
    UPDATE_CHARACTER: 'UPDATE_CHARACTER',
    REMOVE_CHARACTER: 'REMOVE_CHARACTER',
    CREATE_ENCOUNTER: 'CREATE_ENCOUNTER',
    UPDATE_ENCOUNTER: 'UPDATE_ENCOUNTER',
    REMOVE_ENCOUNTER: 'REMOVE_ENCOUNTER',
    SET_ACTIVE_ENCOUNTER: 'SET_ACTIVE_ENCOUNTER',
    CLEAR_ACTIVE_ENCOUNTER: 'CLEAR_ACTIVE_ENCOUNTER',
    CREATE_INITIATIVE: 'CREATE_INITIATIVE',
    UPDATE_INITIATIVE: 'UPDATE_INITIATIVE',
    REMOVE_INITIATIVE: 'REMOVE_INITIATIVE',
    SET_NEXT_TURN: 'SET_NEXT_TURN',
    UPDATE_INITIATIVE_STAMP: 'UPDATE_INITIATIVE_STAMP'
}

module.exports = wsTypes